export const descriptions = {
          "af": "",
          "ar": "",
          "au": "Fictional alphabet in Star Wars",
          "bn": "",
          "ca": "Catalan",
          "cs": "Czech",
          "de": "German",
          "en": "",
          "es": "Spanish",
          "fa": "",
          "fr": "French",
          "he": "",
          "hr": "Croatian",
          "haw": "Hawaiian",
          "id": "",
          "it": "Italian",
          "kln": "Fictional language in StarTrek TV show",
          "la": "Latin",
          "lt": "Lithuanian",
          "hu": "Hungarian",
          "nl": "Dutch",
          "no": "Norwegian",
          "pl": "Polish",
          "pt": "Portuguese",
          "ro": "Romanian",
          "sld": "A German dialect",
          "ev": "A fictional language in The Lord of the Rings book",
          "sk": "Slovak",
          "sl": "Slovenian",
          "sr": "Serbian",
          "fi": "Finnish",
          "sv": "Swedish",
          "vi": "Vietnamese",
          "vu": "Fictional language in StarTrek TV show",
          "ru": "Russian",
          "mr": "Marathi",
          "hi": "Hindi",
          "gu": "Gujarati",
          "ta": "Tamil",
          "kan": "Kanada",
          "si": "Sinhala",
          "th": "Thai",
          "my": "Myanmar",
          "ko": "Korean",
          "jpn": "Japanese",
          "zh": "Chinese",
}